### ISSUE TITLE
ERROR Rack::Lint::LintError:

### ISSUE THREAD

**Issue by johnchourajr** [siteleaf/siteleaf-gem#45]
Hi, I'm setting up my siteleaf dev env. on a new computer, and I'm running into this issue with my server.

I installed the gem, and ran the server, but this error popped up.

```
::1 - - [11/Aug/2015:22:09:34 -0700] "GET /favicon.ico HTTP/1.1" 401 1 0.3448
[2015-08-11 22:09:34] ERROR Rack::Lint::LintError: Content-Length header was 1, but should be 26
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:20:in `assert'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:692:in `verify_content_length'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/lint.rb:716:in `each'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/body_proxy.rb:31:in `each'
	/Library/Ruby/Gems/2.0.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:112:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
	/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```

**Comment by johnchourajr** [comment]
Never mind, found this solution https://twitter.com/siteleaf/status/476572804855631872 

Ran config again.

:)
