### ISSUE TITLE
Error in 2.0.0-pre when trying to config a site

### ISSUE THREAD

**Issue by jdsimcoe** [siteleaf/siteleaf-gem#48]
Here's the error I get when trying to `siteleaf config <SITENAME>` from the command line:

```log
/Users/jdsimcoe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/siteleaf-0.9.23/lib/siteleaf/entity.rb:49:in `attributes=': undefined method `each_pair' for #<Array:0x007ff3d69f6e48> (NoMethodError)
	from /Users/jdsimcoe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/siteleaf-0.9.23/lib/siteleaf/entity.rb:7:in `initialize'
	from /Users/jdsimcoe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/siteleaf-0.9.23/lib/siteleaf/site.rb:9:in `new'
	from /Users/jdsimcoe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/siteleaf-0.9.23/lib/siteleaf/site.rb:9:in `find_by_domain'
	from /Users/jdsimcoe/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/siteleaf-0.9.23/bin/siteleaf:190:in `<top (required)>'
	from /Users/jdsimcoe/.rbenv/versions/2.2.2/bin/siteleaf:23:in `load'
	from /Users/jdsimcoe/.rbenv/versions/2.2.2/bin/siteleaf:23:in `<main>'
```

**Comment by sskylar** [comment]
v2 pre-release is in development, please use the official master instead (currently 0.9.23)

**Comment by jdsimcoe** [comment]
cool @sskylar when do you anticipate `2.0` going live? I'm excited to be able to create a nice CI workflow with Siteleaf once it hits.
