### ISSUE TITLE
Error in Pushing Collections to  Siteleaf. v2

### ISSUE THREAD

**Issue by Amay22** [siteleaf/siteleaf-gem#56]
`siteleaf push` error
Collections are not being pushed into thier respective collection directory instead they end up in pages. The url link for these collection pages has an underscore (_) in the beginning.

**Comment by Amay22** [comment]
@sskylar Thanks I think this issue is fixed

using siteleaf gem version 2.0.0.pre.beta6

`bundle exec siteleaf push`

still results in the following error:-

httparty-0.13.7/lib/httparty/response.rb:71:in `method_missing': undefined method `each_pair' for #<HTTParty::Response:0x007fa893214858> (NoMethodError)
	from /Users/amay/.rbenv/versions/2.1.6/lib/ruby/gems/2.1.0/bundler/gems/siteleaf-gem-87668be190a8/lib/siteleaf/entity.rb:49:in `attributes='
